Removing South from location
thought this worked yesterday, retesting fails again `<main>':
undefined method `[]' for nil:NilClass (NoMethodError) (because it
returns no city)